# Render.com deployment configuration for PromptAgro Backend
# This file tells Render how to build and deploy your FastAPI backend

# Build settings
builds:
  - type: web
    name: promptagro-backend
    env: python
    buildCommand: |
      cd backend
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 2
    
# Environment variables (set these in Render dashboard)
envVars:
  - key: DEBUG
    value: "False"
  - key: HOST  
    value: "0.0.0.0"
  - key: CORS_ORIGINS
    value: "https://your-frontend-domain.onrender.com,http://localhost:3000"
  - key: GEMINI_API_KEY
    sync: false # This should be set manually in Render dashboard for security

# Health check
healthCheckPath: /health

# Auto-deploy settings  
autoDeploy: true
branch: main

# Resource settings
plan: free # or starter/standard for production
region: oregon # or singapore, ohio, etc.

# Static files serving
staticPublishPath: backend/static
